### ISSUE TITLE
Monday night's pre-game feasting

### ISSUE THREAD

**Issue by runicfox** [runicfox/DnD5e#17]
@ecowden - any thoughts on where to order food from on Monday?  I don't mind picking up, but if there's decent delivery place (pizza, Chinese, etc.) that you enjoy, I'm down for anything.

**Comment by ecowden** [comment]
Oooo, great question. 

My standby is Papa John's for pizza. I can order as soon as I get home and have it here pretty quick. 

For variety, Talayna's is a good treat. I don't think they deliver, but it's on the way along olive.

The Chinese around here is nothing special. I usually go with Hunan Express, but it's been years. There might be something awesome that I've missed.

I think I'd lean towards ordering PJ's for Monday, then finding something new and exciting for the week after. But...hey, I'm totally open! Thoughts?

P.S., I love cooking, too. When it gets to be grilling weather,  I'd be delighted to break out the burgers, brats, steaks, etc.

**Comment by runicfox** [comment]
I'm going to close this issue.  We can always raise another one for next week's get-together.
