### ISSUE TITLE
Weekend Gaming? Eh? Eh?

### ISSUE THREAD

**Issue by ecowden** [runicfox/DnD5e#20]
Yeah, I'm really digging this idea. So...umm...what's everyone doing Saturday? :wink:

**Comment by runicfox** [comment]
I think Sam said he was busy this particular Saturday.  I also have to be careful that I don't overextend the good graces of my wife.  Between our Monday night session, and the Tuesday Night/Saturday morning demands of the Half-Marathon training - I'm inching closer to her limit.  That said, Lisa is an avid RPG'er - so I know that she'd be down for playing a temporary character in the campaign (per the group's approval) if we can secure a babysitter.

**Comment by AsmodeusXI** [comment]
Yeah, I'd really only be able to do once a month or so, and even then not overlapping with my other occasional weekend group. So yeah... tough, but hardly impossible.

**Comment by joanne-jjb** [comment]
I'm available given prior notice =)

**Comment by joanne-jjb** [comment]
Reopening this issue! Dare I suggest a D&D extravaganza on the nerdiest of all nerd days.....Pi Day?

Yes indeed, the most historic Pi Day of our lifetimes is Saturday, March 14th, 2015. What better way to celebrating the event than by killing some Cultists and consuming circular foods (parts of a beer bottle are circular, right?) in our best mathy/geeky joke shirts? (they're probably from woot!)

**Comment by ecowden** [comment]
Whoa! I hadn't even thought of it: 3/14/15 really _is_ an epic date!

...unfortunately, we have tentative plans to go to the St. Patrick's day parade that day. :frowning:

**Comment by runicfox** [comment]
@ecowden, you do realize that while you're at the Parada - literally tens of cultists and kobolds will be roaming the countryside near Greenest, doing Tymora knows what - and most importantly, **not** being slain for their delicious experience points, right?  Do you really understand what you're saying, @ecowden.

We're worried about you and this decision you're making.  We're concerned that the fantastical concerns of Faerûn aren't enough to keep you from dabbling in these ridiculous "read world" adventures people are telling you are so important.

We need you, @ecowden.  We need Sparks.  We need you to be the hero who enables the grayish bits of Rinn's morality.  Be the hero.

Also, St. Patrick died a long time ago.  Unless someone plans on resurrecting him as a Lich, I don't think he's worth much XP, or has any loot worth desecrating his corpse over.  Just sayin'.

**Comment by joanne-jjb** [comment]
Additionally, the parade isn't all day and I do live near downtown. Counter-proposal...come to my house, D&D in the morning, parade it up from noon till whenever that's done; then D&D again at my house. I'll even pick you up and drop you guys off at the parade (heck, there may even be shuttles you could take from Soulard! I'm sure McGurks has a passing interest in St. Patrick's Day). I have a couple reserved spots behind my house and live near McGurks.

Space isn't an issue so bring whoever you want since I rent a three story townhouse. Adult non-D&D companions are also free to wander/barcrawl around Soulard. #wewillnotbedenied #giveinevan

**Comment by runicfox** [comment]
Guh. "Parade", and "Real World". See the depths of fat fingering your lack of conviction has wrought? Dammit man, who will help heap words of scorn upon The Dan? Who will help hold the funnel in Panda's mouth as we pour liters of laxative down its throat? 

If not Sparks, then who? 

We can't let Dan get away with this...

**Comment by ecowden** [comment]
Ok, there's some tempting ideas there. Let's chat tonight and see what we can figure out. :wink:

**Comment by joanne-jjb** [comment]
Just as a reminder, we have this Sunday, March 15th after 12:30pm for possible weekend gaming....still happening?

**Comment by runicfox** [comment]
Let me double check with Lisa.

**Comment by ecowden** [comment]
I'm in!

**Comment by runicfox** [comment]
Okay. I'm good to go for Sunday. Are we planning on starting at 12:30 or 1pm?  Can we plan on going until maybe 5 or 5:30pm?

**Comment by joanne-jjb** [comment]
I'm good with all the times so how about 1:00pm - 5:30pm?

**Comment by AsmodeusXI** [comment]
Damn. I can't do this Sunday. Sorry I thought I mentioned that on Monday. :/ Would 22nd be okay instead? SORRY.

**Comment by runicfox** [comment]
No worries @AsmodeusXI.  I don't know if the 22nd will work for me - but we'll figure something out.

**Comment by joanne-jjb** [comment]
regroup on Monday =)

**Comment by runicfox** [comment]
Hey folks.  I'm a no-go for Sunday.  Forgot that I have a birthday party to attend in the afternoon.

**Comment by runicfox** [comment]
I'm going to close this issue.  I referenced being able to possibly place the first weekend in April.  See [Issue 51](https://github.com/runicfox/DnD5e/issues/51)
