### ISSUE TITLE
Dinner February 2nd

### ISSUE THREAD

**Issue by ecowden** [runicfox/DnD5e#29]
Hey all,

Whatcha feel like? I'm cool with pizza again, but I'm also totally open to other ideas.

Eh?

**Comment by AsmodeusXI** [comment]
Yeah, pizza seems fine to me. Do we want to start a buyer rotation?

**Comment by runicfox** [comment]
I'm not sure if Evan (or anyone else) is already aware - but Papa John's has a rewards program.  Every 25 points earned gets you a free pizza.  Our order from last week would have netted 5 points.

That said, I'm totally happy to get the pies tonight.  Are there any requested modifications from last week's order?  I think that there was a pepperoni, and an "all the animals" pizza - and an order of bread sticks.  Does that sound right?

**Comment by joanne-jjb** [comment]
That older looks right to me! Also, Papa John's frequently has coupons and other deals. 

If you enter "Retail25" at check out, you can get 25% off the total order =)

**Comment by runicfox** [comment]
Thanks @joanne-jjb for the 'BLUES3' 50% off code!  I've got dinner ordered.  I'll pick it up on my way over.  See you guys around 5pm.
