### ISSUE TITLE
Dinner February 9th

### ISSUE THREAD

**Issue by runicfox** [runicfox/DnD5e#31]
Any takers?  Moar pizza?

**Comment by AsmodeusXI** [comment]
I'd be glad to grab it. Someone just has to give me the number and all the money saving cheat codes (Also any different foodz that anyone wants).

**Comment by AsmodeusXI** [comment]
DINNER WILL ARRIVE @ 5.

**Comment by runicfox** [comment]
And a delicious dinner it was.  Closing the issue.
