### ISSUE TITLE
Winter Weather Gaming

### ISSUE THREAD

**Issue by AsmodeusXI** [runicfox/DnD5e#37]
Considering that I'm (and I think most others are) WFH today, is the plan to hold off next session until next week? Wanted to gather other thoughts on this since the roads are of poooooor quality.

**Comment by runicfox** [comment]
I'll defer to the group.  Last I heard the snow should stop before 3pm, but that obviously doesn't address any slop that's still on the roads.  @AsmodeusXI and @joanne-jjb have further to drive than I do, so I'd put it in their court.

**Comment by ecowden** [comment]
I will also defer to the group since my drive is rather short. The road outside my house is great -- but I live on a county road with an elementary school, so we get plows about every twenty minutes. :grin: 

If we call it off, do you want to wait until next week or reschedule for another night this week?

**Comment by AsmodeusXI** [comment]
Yeah, I neither trust St. Louis to plow nor St. Louis drivers to not crash into me, so I'd prefer not to drive. What do you think @joanne-jjb ?

As far as the next session goes, I really don't have many other free days in the week, so my vote would be next week, sadly enough.

**Comment by joanne-jjb** [comment]
Unfortunately I don't think I can drive out there, The roads are awful downtown and my little civic can't handle the snow. Till next week then? It's my turn for pizza and I'll be picking up tonic and dry vermouth for the copious amount of gin we have!

**Comment by joanne-jjb** [comment]
This also leaves me no more excuses for not finishing my character sheet
