### ISSUE TITLE
Monday, February 23rd

### ISSUE THREAD

**Issue by runicfox** [runicfox/DnD5e#38]
Just checking in to make sure folks are still on board for tomorrow's gaming.

@joanne-jjb - are you still cool with getting the pizza?

**Comment by ecowden** [comment]
Oh, I'm totally in. Can't wait!

**Comment by AsmodeusXI** [comment]
Can escape driveway = ready to DnD :dancers:

**Comment by joanne-jjb** [comment]
I'm in! Pizza is on. (any preferences on toppings? otherwise I'll be selecting whatever I want plus breadsticks) Also, tonic water and cucumber purchased (gin tonics), and dry vermouth and olive juice (dirty martinis))

And I'll be doing that at lunch =P Salesforce support was hefty this week

**Comment by ecowden** [comment]
Yay!!!

Also, I picked up some tonic water, but not the rest of it...

See you tonight!

Can escape driveway = ready to DnD [image: :dancers:]

—
Reply to this email directly or view it on GitHub
<https://github.com/runicfox/DnD5e/issues/38#issuecomment-75547040>.

**Comment by runicfox** [comment]
Hey @joanne-jjb - not sure if a current deal you know of is better than this: 
![image](https://cloud.githubusercontent.com/assets/1626223/6334400/0aed1a42-bb5a-11e4-88d5-6891200132fc.png)
