### ISSUE TITLE
Dinner tomorrow

### ISSUE THREAD

**Issue by runicfox** [runicfox/DnD5e#46]
I don't know whose turn it is, but does anyone have objections or ideas for something besides pizza?

I'm also okay with doing pizza again, but wanted to broach the subject of menu change.

**Comment by joanne-jjb** [comment]
I'm up for dinner this week! I'm open to any kind of food, but I don't really know the area that well.

Just let me know where to go and what to pick up =)

**Comment by ecowden** [comment]
Ooo...good thinking!

There's plenty of food around my house, but most of it is sit-down fare. For quick and carry-out, we have our choice of Taco Bells and McDonalds and Steak 'n Shake.

What else...

A hair more upscale, Harpo's is practically within walking distance; that could be a fun take out. There's also Addie's Thai House and an El Maguey on the way. We'd probably want to order ahead for any of those.

In a different direction: the weather is nice. We could stop by the grocery store, grab some burgers/dogs/brats/steaks and toss 'em on the barbie. I don't want to steal turns here, but I can probably leave early enough tomorrow to grab stuff on the way home if we want to go in that direction. (Or not!)

**Comment by joanne-jjb** [comment]
lol i think we've triggered Evan's "compulsive host" mode.

Thai, mexican or bbq would be my preference =) I can pick things up on my way over as long as i get everyone's order.

**Comment by AsmodeusXI** [comment]
I'd prefer less on the fast food end, but other than that I'll have anything. Mexican and Thai are particular favorites of mine, but I'm not very picky. :smile:

**Comment by ecowden** [comment]
H'okay, unless anyone has any real preferences, I just rolled a d6 and it came up Mexican. :grin:

**Comment by runicfox** [comment]
The d6 and I concur on Mexican. El Maguey has good food.

**Comment by joanne-jjb** [comment]
Let me know your orders. Or else I'll be rolling d20 on the menu on your behalf! Better hope I don't critically fumble....https://foursquare.com/v/el-maguey-mexican-restaurant/4ae1e22bf964a520578821e3/menu

I'll be leaving around 4:30 to grab the food.

**Comment by runicfox** [comment]
Here's another menu:  http://www.allmenus.com/mo/maryland-heights/55009-el-maguey/menu/

Looks like the one @joanne-jjb posted isn't their full faire.

**Comment by ecowden** [comment]
Chicken fajitas, please! 

Thanks, Joanne!

**Comment by joanne-jjb** [comment]
Sam is in serious danger of me using Random() for his dinner selection.
