### ISSUE TITLE
Rinn

### ISSUE THREAD

**Issue by runicfox** [runicfox/DnD5e#50]
A couple of items.

First, the subject of leveling up Rinn.

I'm exploring ways to boost our firepower, and honestly adding a fourth level of Cleric to the mix doesn't do much in that regard.

I'm primarily looking at adding a level of Warlock.  Strategically, it sets Rinn up to be able to bring some serious voodoo down on the baddies.  Tactically, there are a few things I can do out of the gate (even as a 1st level Warlock) that could better enable Sparks to have even more success when dishing out the evocation spells.

That last idea is primarily fueled using the 1st level Warlock spell _Hex_.  _Hex_ is cast as a bonus action, has a range of 90 feet, and can last up to an hour.  A creature in range is chosen, and for the duration of the spell (or the creatures remaining HP), any attack that Rinn does deals an extra 1d6 points of damage, and I would choose any one ability to have that creature have disadvantage on saves.  So naturally, I'm thinking "Golly, would it be nice to have a baddie's Dex save be crippled when rolling for half damage against Sparks' (@ecowden)  :fire: _Burning Hands_ :fire:  (or soon, :boom:  _Fireball_ :boom:)?"

I'd also get 2 cantrips.  _Eldritch Blast_ has a range of 120' and deals 1d10 damage on successful spell attack :point_right: -------------------------- (wait for it...) --------- when paired with _True Strike_ --------- it gives me advantage to whack baddies at a respectable distance with a fair assurance of making the connection-------- :boom: :dragon: :skull: 

There are other notable benefits to taking a level of Warlock.  Depending on the type of patron I choose, I could gain the ability to communicate telepathically with any sentient creature within 30' that I have line of sight on.  That's a massive tactical advantage when you consider that Rinn would effectively act as a communications node for relaying information silently within the party.

If you've got a copy of the PHB out and you're reading up on the Warlock class, you're probably realizing from that last ability that I'm looking at the Great Old One patron-type.  So you might be saying to yourself, "Uh, yeah that's cool and stuff - but Rinn's just a little unhinged already.  Are we sure we want was basically amounts to Cthulu complementing his worship of a trickster god?"

I've been giving some thought to the last few sessions, and I've concluded that I'm not really digging this dark side of Rinn.  I'm okay with a little crazy, but the sadism isn't really where I want to take that character.

I'm keeping the ball-bearings though.  Just probably won't use them as I had described.

**Comment by runicfox** [comment]
Also, I was talking to Lisa about this idea I have with Rinn and she was curious why it would make sense (from a story or character development perspective) to go this route.  The way I see it, Rinn has had no less than 3 separate brushes with death (2 at the hands of Cyanwrath).  I don't think that it's unreasonable that somewhere in the dark tunnel (where on one end is the white light, and the other is Sparks and/or Kurtzar dragging him back to the land of the stabilized) that he wouldn't attract the attention of his new Great Old One patron.

Rinn's introduction to this alien intelligence will have the effect of taming his more disruptive nature, and providing him with some additional tools to work a more subtle mission for his god.

**Comment by ecowden** [comment]
Ooo, lots of good possibilities there, enough to send me back to my PHB re re-read those other classes.

From a gameplay perspective, I like where you're going with this. We can deal plenty of damage when the dice roll our way, but that's proving a pretty unreliable strategy. We need ways to manipulate the world, to push things our way. Rinn could fit that role nicely.

The hideous tentacle monster encounter was a very teachable moment for me. If we stood there and just tried to blow it up, we'd all be dead. We had to think of something more creative, and your idea to distract it saved the day. We probably 

(Aside: I also felt that it was also a lesson on being a good DM. That whole encounter was a great, edge-of-our-seat, we-could-all-die-at-any-moment action. @AsmodeusXI made it super exciting, while also finding a way to let us survive by the skin of our teeth. Kudos!)

At any rate, I like the character development perspective a lot. (I have my own thoughts on how Sparks is evolving with inspiration from Rinn, but I don't want to steal your issue.  :wink:) 

I'm curious: if you multiclassed as a warlock, would you continue leveling up warlock or cleric?

**Comment by AsmodeusXI** [comment]
I'm glad you enjoyed it. I think I could've played it better myself, but that's just me.

I think that every D&D player has a first moment when they realize that there are things out there that are stronger than they are that should be avoided. Sometimes they learn that with a dead character. You guys lucked out alive. :smile: (seriously though if Sparks wasn't apparently a dragon-ninja you'd all be Roper food)

**Comment by runicfox** [comment]
@ecowden, when we hit level 5 I'd have do some serious weighing of the benefits of Warlock 2 (spells, incantations, etc) against Cleric 4 (attribute increase, another Cleric cantrip).  My first inclination is to bring my Warlock level closer in line with my Cleric level, and then maybe bounce between the two.

I also think that it's particularly interesting to have the "normal" looking half-elf Rinn be the "bad cop" to the scaly dragonborn "good cop".  Nice role reversal to keep prisoners on their feet.

The multiclassing with multiple casting types isn't immediately clear, but it's really powerful.  You get to pool both the spells per day for both classes and use that pool in the spells you have available for either class.  In other words, I can burn Cleric slots for Warlock spells and vice versa.

It *almost* makes up for missing out on the ability bump I would have gotten from Cleric 4.  :smile:

**Comment by ecowden** [comment]
Whoa, I thought the attribute bonus was for making level 4, not for making fourth level in the class. You must seriously want this. :grin: 

I think this will be fun...now we just have to survive two weeks of wait! :wink: 

P.S. Is dragon ninja a real class? I'm totally taking some levels in that...
