### ISSUE TITLE
Next Monday

### ISSUE THREAD

**Issue by runicfox** [runicfox/DnD5e#51]
I'm a no-go for gaming next Monday.  Lisa's out of town at a conference, so I'll be trying to get Fia to roll up a character.  I may have to concede that "Princess Superhero" is a valid class.

That said, I feel like I owe the party a long session on a weekend.  Lisa is leaving Saturday morning, so that leaves this weekend as a definite no-go.  The following weekend is Easter.  I'll probably have a family obligation or something on Sunday - but is Saturday (or possibly even a later Friday night) a possibility?

**Comment by ecowden** [comment]
Yeah, I could totally do Saturday the 4th! :facepunch: 

Friday the 3rd is iffy. We have a tentative happy hour planned, though those kinds of things tend to fall through.

**Comment by runicfox** [comment]
No worries.  Saturday would be my preference anyway, so that's perfect.

**Comment by joanne-jjb** [comment]
Saturday works for me as well =) Prefer not Friday just because of Good Friday. I'm not the greatest catholic but I would like to avoid that one

**Comment by joanne-jjb** [comment]
It's official! This Saturday, April 3 at 2:00pm (at Evan's House....Sam, let me know if you need a ride!) Evan's turn for food =)

Duration will be as long as we'd like to play/Sam has material prepared.

**Comment by joanne-jjb** [comment]
Hi Evan! Not sure if you read Matt's email but he can't make today...Monday for sure though.

Also, can you send us your number? we dont seem to have it. Mine is 562 458 0632

**Comment by ecowden** [comment]
Hey Joanne!

Yep, I got the news. Sorry, didn't hit reply all!

My phone number is 314-308-5058.

See you all Monday!

- E
