### ISSUE TITLE
Questions to the DM

### ISSUE THREAD

**Issue by ecowden** [runicfox/DnD5e#56]
* Would an unarmed strike / monk weapon work with the Defensive Dualist feat (p.165)? What about the Dual Wielder feat? The Monk's Martial Arts feature (p. 78) makes these use Dex instead of Strength anyway, which feels a lot like a finesse weapon to me. I'm trying to brainstorm ways to...you know...not die.
* Any special considerations for starting gold and equipment with these new characters?

**Comment by AsmodeusXI** [comment]
1) There are certain monk weapons that are finesse weapons (such as shortswords), but I wouldn't count unarmed strikes as finesse by default. (See: http://rpg.stackexchange.com/questions/47349/can-a-monk-use-trigger-defensive-duelist-while-wielding-a-monk-weapon-or-unarme) On the other hand, if you wanna try it, we can see if it would be game breaking. Similarly, Dual Wielder specifies that you are wielding two one-handed melee weapons, so unarmed strikes wouldn't apply (as before: http://rpg.stackexchange.com/questions/47951/can-monks-gain-the-benefit-of-the-dual-wielder-feat-with-their-unarmed-strikes?rq=1)

2) I'll open another issue shortly...

**Comment by ecowden** [comment]
Dude, there's an RPG StackExchange!? :grinning: : 

As for the feats...no big deal there for me. When I started twiddling with characters, my first instinct was, "how can I make something with the highest AC possible?" In hindsight, I don't think it's even that great of an idea. I've probably found ~~worse~~ better ways to fiddle with feats since then.

Also, if I'm being obnoxious, please let me know... :grimacing:

**Comment by AsmodeusXI** [comment]
Not hardly! These rules questions are important. :smile: 

I'm just terrified because you seem to have become a powergamer and I'm probably not equipped to handle that. :cold_sweat:

**Comment by ecowden** [comment]
Ooo...sorry... :grin: 

I suppose now we know what happens when I stay home for a week and relax, without the normal challenges of the day-to-day...

I admit it, I do have natural powergamer tendencies, though I've been carefully setting them on the back burner during this game. I suppose dying activated that part of my brain that really likes playing Civilization on Deity level, 'cause you've gotta get really creative to survive as long as possible. Without that death, I'd never be brainstorming the crazy things a party of Aarakocra could pull off, in and out of combat. Or a phalanx combining _polearm master_ with _sentinel_. Etc. :neckbeard: 

But seriously, I don't want to be That Guy. If I ever go off the deep end, just speak up.
