### ISSUE TITLE
Session Date Change for this Week

### ISSUE THREAD

**Issue by AsmodeusXI** [runicfox/DnD5e#61]
I mentioned this to Joanne and Matt on Friday, but I figured I'd get it out here for official-ness' sake and for Evan (obviously).

This week I wanted to have our session on Wednesday 5/6 instead of on 5/4. Would that be possible? I think the aforementioned two were a (generally) green light, but I want to make sure I have confirmation before I declare the rescheduling a reality.

Thanks!

**Comment by ecowden** [comment]
Oh yeah, totally cool for me. 

See y'all Wednesday!

**Comment by runicfox** [comment]
Just confirming that I'm good to go for the day change this week.  I know that @joanne-jjb and I WFH on Wednesdays.  What about you @AsmodeusXI?

**Comment by AsmodeusXI** [comment]
I'll be at work but I'll be at Evan's at 5 as per usual!

**Comment by joanne-jjb** [comment]
Since this issue isnt closed yet I'll post here! 

For Memorial Day, I don't think I can make it to Evan's still 6:30pm. Sorry its so late everyone! Are we still on for Monday?

**Comment by runicfox** [comment]
No worries, @joanne-jjb.  I don't think that I'll be able to make it after all (irrespective of you're arrival).

Sorry folks.  It's possible that I might be able to do a different day later in the week.
